import "./globals.css";
import NextLoader from "@/components/NextTopLoader";
import { Inter, Roboto_Mono } from "next/font/google";
import { SnackbarProvider } from "@/components/Snackbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Qaza Namaz Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${inter.variable} ${robotoMono.variable}`}
      >
        <SnackbarProvider>
          {" "}
          <NextLoader />
          {children}
        </SnackbarProvider>
      </body>
    </html>
  );
}
